os:
  - linux
  - osx
language: node_js
install:
  - npm install -g codecov
node_js:
  - "node"
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
script:
  - node --version
  - npm --version
  - npm run test
  - if [[ ${TRAVIS_NODE_VERSION} == node && ${TRAVIS_OS_NAME} == linux ]]; then npm run coverage; codecov; fi;
