branches:
  only:
    - master
    - remove-cli
image:
  # - Visual Studio 2019
  - Ubuntu
  # - macOS
init:
  - git config --global core.autocrlf true

environment:
  matrix:
    # - nodejs_version: 15
    # - nodejs_version: 14
    # - nodejs_version: 13
    # - nodejs_version: 12
    - nodejs_version: 11
      run_coverage: on
    - nodejs_version: 10
    # - nodejs_version: 9
    # - nodejs_version: 8

platform:
  - x86
  # - x64

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - ps: Install-Product node $env:nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm test
  - matrix:
      only:
        - image: Ubuntu
    install:
      - nvm use $nodejs_version
    test_script:
      - node --version
      - npm --version
      - '[ -z "$run_coverage" ] && npm test'
      - '[ -n "$run_coverage" ] && npm run coverage'
      - '[ -n "$run_coverage" ] && npx codecov'

build: off
